name: CI

on:
  issues:
    types: [opened, edited]

jobs:
  add-assigness:
    runs-on: ubuntu-latest
    steps:
      - name: 安装依赖
        run: pip install pygithub pandas click openpyxl
        
      - name: clone检验仓库
        run: |
          git clone https://x-access-token:${{ secrets.GTCI }}@github.com/GT-ZhangAcer/CertificateInspectionBackend
          
      - name: 验证持有人信息
        run: | 
          cd CertificateInspectionBackend
          python query.py -i ${{ github.event.issue.number }}
      
